brew "ansible"
brew "aspell"
brew "atmos"
brew "awscli"
brew "cmake"
brew "cmark"
brew "cmark-gfm"
brew "coreutils"
# brew "cpanminus"
# brew "cpm"
brew "direnv"
brew "docutils"
brew "fzf"
brew "gawk"
brew "gettext"
brew "gh"
brew "git"
brew "gnutls"
brew "go"
brew "goenv"
# brew "golangci-lint"
brew "gpatch"
brew "hadolint"
brew "helm"
brew "hugo"
brew "icu4c"
brew "jq"
# brew "just"
brew "k9s"
brew "krb5"
brew "krew"
brew "kubectl"
brew "kubectx"
# brew "leapp"
brew "libpq"
brew "libressl"
brew "libtermkey"
brew "libxml2"
brew "libxslt"
brew "llvm"
brew "lzip"
# brew "multimarkdown"
brew "mysql-client"
brew "perl"
brew "pgxnclient"
brew "pinentry-mac"
brew "pinentry"
brew "pre-commit"
brew "python"
brew "readline"
brew "ripgrep"
brew "rustup-init"
brew "shellcheck"
brew "starship"
brew "terraform-docs"
brew "terraform"
brew "tree"
brew "wget"
brew "xz"
brew "yq"
brew "zlib"
brew "zsh"
cask "emacs"
# cask "google-cloud-sdk"
tap "sqitchers/sqitch"

# brew "asciidoc"
# brew "asciidoctor"
# brew "docbook-xsl"
# brew "docbook"
# brew "fop"
# brew "mysql"
# brew "netpbm"
# brew "node"
# brew "openssl@1.1"
# brew "psutils"
# brew "unbound"
# brew "youtube-dl"
# cask "visual-studio-code"
